/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0-beta.9.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface AuditLog {
  'id' : bigint,
  'action' : string,
  'target' : [] | [Principal],
  'performedBy' : Principal,
  'timestamp' : bigint,
  'postId' : [] | [bigint],
}
export interface Message {
  'id' : bigint,
  'to' : Principal,
  'content' : string,
  'from' : Principal,
  'timestamp' : bigint,
}
export interface Notification {
  'from' : Principal,
  'kind' : { 'repost' : null } |
    { 'like' : null } |
    { 'mention' : null } |
    { 'reply' : null } |
    { 'follow' : null },
  'timestamp' : bigint,
  'postId' : [] | [bigint],
}
export interface Post {
  'id' : bigint,
  'deleted' : boolean,
  'content' : string,
  'hashtags' : Array<string>,
  'originalPostId' : [] | [bigint],
  'author' : Principal,
  'mediaIds' : Array<string>,
  'likes' : bigint,
  'timestamp' : bigint,
  'replies' : bigint,
  'reposts' : bigint,
}
export interface Report {
  'id' : bigint,
  'status' : { 'pending' : null } |
    { 'reviewed' : null } |
    { 'actioned' : null },
  'reportedBy' : Principal,
  'timestamp' : bigint,
  'reason' : string,
  'postId' : bigint,
}
export interface UserProfile {
  'bio' : string,
  'languagePreference' : string,
  'username' : string,
  'displayName' : string,
  'profilePicture' : [] | [string],
  'suspended' : boolean,
}
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _CaffeineStorageCreateCertificateResult {
  'method' : string,
  'blob_hash' : string,
}
export interface _CaffeineStorageRefillInformation {
  'proposed_top_up_amount' : [] | [bigint],
}
export interface _CaffeineStorageRefillResult {
  'success' : [] | [boolean],
  'topped_up_amount' : [] | [bigint],
}
export interface _SERVICE {
  '_caffeineStorageBlobIsLive' : ActorMethod<[Uint8Array], boolean>,
  '_caffeineStorageBlobsToDelete' : ActorMethod<[], Array<Uint8Array>>,
  '_caffeineStorageConfirmBlobDeletion' : ActorMethod<
    [Array<Uint8Array>],
    undefined
  >,
  '_caffeineStorageCreateCertificate' : ActorMethod<
    [string],
    _CaffeineStorageCreateCertificateResult
  >,
  '_caffeineStorageRefillCashier' : ActorMethod<
    [[] | [_CaffeineStorageRefillInformation]],
    _CaffeineStorageRefillResult
  >,
  '_caffeineStorageUpdateGatewayPrincipals' : ActorMethod<[], undefined>,
  'addAuditLog' : ActorMethod<
    [string, [] | [Principal], [] | [bigint]],
    undefined
  >,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'blockUser' : ActorMethod<[Principal], undefined>,
  'createPost' : ActorMethod<
    [string, Array<string>, Array<string>, [] | [bigint]],
    bigint
  >,
  'deletePost' : ActorMethod<[bigint], undefined>,
  'followUser' : ActorMethod<[Principal], undefined>,
  'getAuditLogs' : ActorMethod<[], Array<AuditLog>>,
  'getBlockList' : ActorMethod<[Principal], Array<Principal>>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getFollowers' : ActorMethod<[Principal], Array<Principal>>,
  'getFollowing' : ActorMethod<[Principal], Array<Principal>>,
  'getMessages' : ActorMethod<[Principal], Array<Message>>,
  'getNotifications' : ActorMethod<[], Array<Notification>>,
  'getPost' : ActorMethod<[bigint], [] | [Post]>,
  'getPostsByAuthor' : ActorMethod<[Principal], Array<Post>>,
  'getRecentChats' : ActorMethod<[], Array<[Principal, bigint]>>,
  'getReports' : ActorMethod<[], Array<Report>>,
  'getTimeline' : ActorMethod<[], Array<Post>>,
  'getTrendingHashtags' : ActorMethod<[], Array<[string, bigint]>>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'initializeAccessControl' : ActorMethod<[], undefined>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'likePost' : ActorMethod<[bigint], undefined>,
  'reportPost' : ActorMethod<[bigint, string], undefined>,
  'requestDataDeletion' : ActorMethod<[], undefined>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'sendMessage' : ActorMethod<[Principal, string], undefined>,
  'suspendUser' : ActorMethod<[Principal], undefined>,
  'takedownPost' : ActorMethod<[bigint], undefined>,
  'unblockUser' : ActorMethod<[Principal], undefined>,
  'unfollowUser' : ActorMethod<[Principal], undefined>,
  'unlikePost' : ActorMethod<[bigint], undefined>,
  'unsuspendUser' : ActorMethod<[Principal], undefined>,
  'updateReportStatus' : ActorMethod<
    [
      bigint,
      { 'pending' : null } |
        { 'reviewed' : null } |
        { 'actioned' : null },
    ],
    undefined
  >,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];