/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0-beta.9.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const _CaffeineStorageCreateCertificateResult = IDL.Record({
  'method' : IDL.Text,
  'blob_hash' : IDL.Text,
});
export const _CaffeineStorageRefillInformation = IDL.Record({
  'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
});
export const _CaffeineStorageRefillResult = IDL.Record({
  'success' : IDL.Opt(IDL.Bool),
  'topped_up_amount' : IDL.Opt(IDL.Nat),
});
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const AuditLog = IDL.Record({
  'id' : IDL.Nat,
  'action' : IDL.Text,
  'target' : IDL.Opt(IDL.Principal),
  'performedBy' : IDL.Principal,
  'timestamp' : IDL.Int,
  'postId' : IDL.Opt(IDL.Nat),
});
export const UserProfile = IDL.Record({
  'bio' : IDL.Text,
  'languagePreference' : IDL.Text,
  'username' : IDL.Text,
  'displayName' : IDL.Text,
  'profilePicture' : IDL.Opt(IDL.Text),
  'suspended' : IDL.Bool,
});
export const Message = IDL.Record({
  'id' : IDL.Nat,
  'to' : IDL.Principal,
  'content' : IDL.Text,
  'from' : IDL.Principal,
  'timestamp' : IDL.Int,
});
export const Notification = IDL.Record({
  'from' : IDL.Principal,
  'kind' : IDL.Variant({
    'repost' : IDL.Null,
    'like' : IDL.Null,
    'mention' : IDL.Null,
    'reply' : IDL.Null,
    'follow' : IDL.Null,
  }),
  'timestamp' : IDL.Int,
  'postId' : IDL.Opt(IDL.Nat),
});
export const Post = IDL.Record({
  'id' : IDL.Nat,
  'deleted' : IDL.Bool,
  'content' : IDL.Text,
  'hashtags' : IDL.Vec(IDL.Text),
  'originalPostId' : IDL.Opt(IDL.Nat),
  'author' : IDL.Principal,
  'mediaIds' : IDL.Vec(IDL.Text),
  'likes' : IDL.Nat,
  'timestamp' : IDL.Int,
  'replies' : IDL.Nat,
  'reposts' : IDL.Nat,
});
export const Report = IDL.Record({
  'id' : IDL.Nat,
  'status' : IDL.Variant({
    'pending' : IDL.Null,
    'reviewed' : IDL.Null,
    'actioned' : IDL.Null,
  }),
  'reportedBy' : IDL.Principal,
  'timestamp' : IDL.Int,
  'reason' : IDL.Text,
  'postId' : IDL.Nat,
});

export const idlService = IDL.Service({
  '_caffeineStorageBlobIsLive' : IDL.Func(
      [IDL.Vec(IDL.Nat8)],
      [IDL.Bool],
      ['query'],
    ),
  '_caffeineStorageBlobsToDelete' : IDL.Func(
      [],
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      ['query'],
    ),
  '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      [],
      [],
    ),
  '_caffeineStorageCreateCertificate' : IDL.Func(
      [IDL.Text],
      [_CaffeineStorageCreateCertificateResult],
      [],
    ),
  '_caffeineStorageRefillCashier' : IDL.Func(
      [IDL.Opt(_CaffeineStorageRefillInformation)],
      [_CaffeineStorageRefillResult],
      [],
    ),
  '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
  'addAuditLog' : IDL.Func(
      [IDL.Text, IDL.Opt(IDL.Principal), IDL.Opt(IDL.Nat)],
      [],
      [],
    ),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'blockUser' : IDL.Func([IDL.Principal], [], []),
  'createPost' : IDL.Func(
      [IDL.Text, IDL.Vec(IDL.Text), IDL.Vec(IDL.Text), IDL.Opt(IDL.Nat)],
      [IDL.Nat],
      [],
    ),
  'deletePost' : IDL.Func([IDL.Nat], [], []),
  'followUser' : IDL.Func([IDL.Principal], [], []),
  'getAuditLogs' : IDL.Func([], [IDL.Vec(AuditLog)], ['query']),
  'getBlockList' : IDL.Func(
      [IDL.Principal],
      [IDL.Vec(IDL.Principal)],
      ['query'],
    ),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getFollowers' : IDL.Func(
      [IDL.Principal],
      [IDL.Vec(IDL.Principal)],
      ['query'],
    ),
  'getFollowing' : IDL.Func(
      [IDL.Principal],
      [IDL.Vec(IDL.Principal)],
      ['query'],
    ),
  'getMessages' : IDL.Func([IDL.Principal], [IDL.Vec(Message)], ['query']),
  'getNotifications' : IDL.Func([], [IDL.Vec(Notification)], ['query']),
  'getPost' : IDL.Func([IDL.Nat], [IDL.Opt(Post)], ['query']),
  'getPostsByAuthor' : IDL.Func([IDL.Principal], [IDL.Vec(Post)], ['query']),
  'getRecentChats' : IDL.Func(
      [],
      [IDL.Vec(IDL.Tuple(IDL.Principal, IDL.Int))],
      ['query'],
    ),
  'getReports' : IDL.Func([], [IDL.Vec(Report)], ['query']),
  'getTimeline' : IDL.Func([], [IDL.Vec(Post)], ['query']),
  'getTrendingHashtags' : IDL.Func(
      [],
      [IDL.Vec(IDL.Tuple(IDL.Text, IDL.Nat))],
      ['query'],
    ),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'initializeAccessControl' : IDL.Func([], [], []),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'likePost' : IDL.Func([IDL.Nat], [], []),
  'reportPost' : IDL.Func([IDL.Nat, IDL.Text], [], []),
  'requestDataDeletion' : IDL.Func([], [], []),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'sendMessage' : IDL.Func([IDL.Principal, IDL.Text], [], []),
  'suspendUser' : IDL.Func([IDL.Principal], [], []),
  'takedownPost' : IDL.Func([IDL.Nat], [], []),
  'unblockUser' : IDL.Func([IDL.Principal], [], []),
  'unfollowUser' : IDL.Func([IDL.Principal], [], []),
  'unlikePost' : IDL.Func([IDL.Nat], [], []),
  'unsuspendUser' : IDL.Func([IDL.Principal], [], []),
  'updateReportStatus' : IDL.Func(
      [
        IDL.Nat,
        IDL.Variant({
          'pending' : IDL.Null,
          'reviewed' : IDL.Null,
          'actioned' : IDL.Null,
        }),
      ],
      [],
      [],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const _CaffeineStorageCreateCertificateResult = IDL.Record({
    'method' : IDL.Text,
    'blob_hash' : IDL.Text,
  });
  const _CaffeineStorageRefillInformation = IDL.Record({
    'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
  });
  const _CaffeineStorageRefillResult = IDL.Record({
    'success' : IDL.Opt(IDL.Bool),
    'topped_up_amount' : IDL.Opt(IDL.Nat),
  });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const AuditLog = IDL.Record({
    'id' : IDL.Nat,
    'action' : IDL.Text,
    'target' : IDL.Opt(IDL.Principal),
    'performedBy' : IDL.Principal,
    'timestamp' : IDL.Int,
    'postId' : IDL.Opt(IDL.Nat),
  });
  const UserProfile = IDL.Record({
    'bio' : IDL.Text,
    'languagePreference' : IDL.Text,
    'username' : IDL.Text,
    'displayName' : IDL.Text,
    'profilePicture' : IDL.Opt(IDL.Text),
    'suspended' : IDL.Bool,
  });
  const Message = IDL.Record({
    'id' : IDL.Nat,
    'to' : IDL.Principal,
    'content' : IDL.Text,
    'from' : IDL.Principal,
    'timestamp' : IDL.Int,
  });
  const Notification = IDL.Record({
    'from' : IDL.Principal,
    'kind' : IDL.Variant({
      'repost' : IDL.Null,
      'like' : IDL.Null,
      'mention' : IDL.Null,
      'reply' : IDL.Null,
      'follow' : IDL.Null,
    }),
    'timestamp' : IDL.Int,
    'postId' : IDL.Opt(IDL.Nat),
  });
  const Post = IDL.Record({
    'id' : IDL.Nat,
    'deleted' : IDL.Bool,
    'content' : IDL.Text,
    'hashtags' : IDL.Vec(IDL.Text),
    'originalPostId' : IDL.Opt(IDL.Nat),
    'author' : IDL.Principal,
    'mediaIds' : IDL.Vec(IDL.Text),
    'likes' : IDL.Nat,
    'timestamp' : IDL.Int,
    'replies' : IDL.Nat,
    'reposts' : IDL.Nat,
  });
  const Report = IDL.Record({
    'id' : IDL.Nat,
    'status' : IDL.Variant({
      'pending' : IDL.Null,
      'reviewed' : IDL.Null,
      'actioned' : IDL.Null,
    }),
    'reportedBy' : IDL.Principal,
    'timestamp' : IDL.Int,
    'reason' : IDL.Text,
    'postId' : IDL.Nat,
  });
  
  return IDL.Service({
    '_caffeineStorageBlobIsLive' : IDL.Func(
        [IDL.Vec(IDL.Nat8)],
        [IDL.Bool],
        ['query'],
      ),
    '_caffeineStorageBlobsToDelete' : IDL.Func(
        [],
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        ['query'],
      ),
    '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        [],
        [],
      ),
    '_caffeineStorageCreateCertificate' : IDL.Func(
        [IDL.Text],
        [_CaffeineStorageCreateCertificateResult],
        [],
      ),
    '_caffeineStorageRefillCashier' : IDL.Func(
        [IDL.Opt(_CaffeineStorageRefillInformation)],
        [_CaffeineStorageRefillResult],
        [],
      ),
    '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
    'addAuditLog' : IDL.Func(
        [IDL.Text, IDL.Opt(IDL.Principal), IDL.Opt(IDL.Nat)],
        [],
        [],
      ),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'blockUser' : IDL.Func([IDL.Principal], [], []),
    'createPost' : IDL.Func(
        [IDL.Text, IDL.Vec(IDL.Text), IDL.Vec(IDL.Text), IDL.Opt(IDL.Nat)],
        [IDL.Nat],
        [],
      ),
    'deletePost' : IDL.Func([IDL.Nat], [], []),
    'followUser' : IDL.Func([IDL.Principal], [], []),
    'getAuditLogs' : IDL.Func([], [IDL.Vec(AuditLog)], ['query']),
    'getBlockList' : IDL.Func(
        [IDL.Principal],
        [IDL.Vec(IDL.Principal)],
        ['query'],
      ),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getFollowers' : IDL.Func(
        [IDL.Principal],
        [IDL.Vec(IDL.Principal)],
        ['query'],
      ),
    'getFollowing' : IDL.Func(
        [IDL.Principal],
        [IDL.Vec(IDL.Principal)],
        ['query'],
      ),
    'getMessages' : IDL.Func([IDL.Principal], [IDL.Vec(Message)], ['query']),
    'getNotifications' : IDL.Func([], [IDL.Vec(Notification)], ['query']),
    'getPost' : IDL.Func([IDL.Nat], [IDL.Opt(Post)], ['query']),
    'getPostsByAuthor' : IDL.Func([IDL.Principal], [IDL.Vec(Post)], ['query']),
    'getRecentChats' : IDL.Func(
        [],
        [IDL.Vec(IDL.Tuple(IDL.Principal, IDL.Int))],
        ['query'],
      ),
    'getReports' : IDL.Func([], [IDL.Vec(Report)], ['query']),
    'getTimeline' : IDL.Func([], [IDL.Vec(Post)], ['query']),
    'getTrendingHashtags' : IDL.Func(
        [],
        [IDL.Vec(IDL.Tuple(IDL.Text, IDL.Nat))],
        ['query'],
      ),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'initializeAccessControl' : IDL.Func([], [], []),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'likePost' : IDL.Func([IDL.Nat], [], []),
    'reportPost' : IDL.Func([IDL.Nat, IDL.Text], [], []),
    'requestDataDeletion' : IDL.Func([], [], []),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'sendMessage' : IDL.Func([IDL.Principal, IDL.Text], [], []),
    'suspendUser' : IDL.Func([IDL.Principal], [], []),
    'takedownPost' : IDL.Func([IDL.Nat], [], []),
    'unblockUser' : IDL.Func([IDL.Principal], [], []),
    'unfollowUser' : IDL.Func([IDL.Principal], [], []),
    'unlikePost' : IDL.Func([IDL.Nat], [], []),
    'unsuspendUser' : IDL.Func([IDL.Principal], [], []),
    'updateReportStatus' : IDL.Func(
        [
          IDL.Nat,
          IDL.Variant({
            'pending' : IDL.Null,
            'reviewed' : IDL.Null,
            'actioned' : IDL.Null,
          }),
        ],
        [],
        [],
      ),
  });
};

export const init = ({ IDL }) => { return []; };